### ISSUE TITLE
I saw this same maturity model from another guy

### ISSUE THREAD

**Issue by paulesco** [joelparkerhenderson/maturity_models#7]
I saw this same maturity model by CHRISTIAN VERSTRAETE in this page, and he never refers it as a HPE maturity model:
[](https://cloudsourceblog.com/2016/11/15/building-an-integrated-agiledevops-maturity-model-showing-how-to-progress/)

https://cloudsourceblog.com/2016/11/15/building-an-integrated-agiledevops-maturity-model-showing-how-to-progress/

why?

**Comment by joelparkerhenderson** [comment]
Christian Verstraete leads the CloudSource blog, and also is the Chief Technologist for Cloud Solutions, Hewlett Packard Enterprise (HPE). The blog post and model showed up in the CloudSource blog site and also in the HPE community site forums.

In general, my experience with many companies is that they typically don't name maturity models, and also derive information from many other maturity models, such as how Christian Verstraete described deriving his from a ThoughtWorks maturity model.

As far as I know, he's active on Twitter and still writes for the CloudSource blog and still works for HPE, if you want to ask him if his model has a name.
